"""add pumpTimer

Revision ID: 5fdccc2854ae
Revises: bfef19805110
Create Date: 2026-09-12 20:25:46.623909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fdccc2854ae'
down_revision: Union[str, Sequence[str], None] = 'bfef19805110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('podDataLog', 'podID',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('podDataLog_podID_fkey'), 'podDataLog', type_='foreignkey')
    op.create_foreign_key(
    'fk_podDataLog_podID_pods',
    'podDataLog',
    'pods',
    ['podID'],
    ['podID'],
    ondelete='SET NULL'
)
    op.drop_column('podLogs', 'created_at')
    op.add_column('pods', sa.Column('podPumpTimer', sa.Integer(), nullable=True))
    op.drop_column('pods', 'created_at')
    op.alter_column('systemLogs', 'deviceID',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('systemLogs', 'deviceID',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('pods', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pods', 'podPumpTimer')
    op.add_column('podLogs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'fk_podDataLog_podID_pods',
    'podDataLog',
    type_='foreignkey'
)
    op.create_foreign_key(op.f('podDataLog_podID_fkey'), 'podDataLog', 'pods', ['podID'], ['podID'])
    op.alter_column('podDataLog', 'podID',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
